### ISSUE TITLE
Repository link is incorrect

### ISSUE THREAD

**Issue by MinusGix** [Zooce/lapce-gruvbox-ish#1]
I noticed that when installing the plugin in Lapce, I wasn't able to change themes to this, so I looked at the files:
https://github.com/Zooce/lapce-gruvbox-ish/blob/main/plugin.toml#L6  
Though I'm uncertain that this is actually the cause, and it might be something else.

**Comment by Zooce** [comment]
Thanks @MinusGix - thanks a good catch!
